# Generated by Django 4.2.14 on 2025-01-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(default='x.jpg', upload_to='img/lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/subjects/'),
        ),
    ]
