# Generated by Django 5.1.5 on 2025-01-20 19:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='explanation',
            field=tinymce.models.HTMLField(default='fg'),
            preserve_default=False,
        ),
    ]
