# Generated by Django 4.2.16 on 2025-01-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0003_alter_lesson_subject_alter_lesson_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/subjects/'),
        ),
    ]
