# Generated by Django 4.2.16 on 2025-01-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0004_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/subjects/'),
        ),
    ]
